In [2]:
!pip install kmodes

import numpy as np
import pandas as pd

from kmodes.kprototypes import KPrototypes

#import data#
marketing_df= pd.read_excel (r'D:\Data Science\Python\Github\Unsupervised Machine learning\Cluster analysis data.xlsx')
marketing_df.head()

Requirement already satisfied: kmodes in c:\users\atefg\anaconda3\lib\site-packages (0.11.0)
Requirement already satisfied: scipy>=0.13.3 in c:\users\atefg\anaconda3\lib\site-packages (from kmodes) (1.5.0)
Requirement already satisfied: numpy>=1.10.4 in c:\users\atefg\anaconda3\lib\site-packages (from kmodes) (1.18.5)
Requirement already satisfied: scikit-learn>=0.22.0 in c:\users\atefg\anaconda3\lib\site-packages (from kmodes) (0.23.1)
Requirement already satisfied: joblib>=0.11 in c:\users\atefg\anaconda3\lib\site-packages (from kmodes) (0.16.0)
Requirement already satisfied: threadpoolctl>=2.0.0 in c:\users\atefg\anaconda3\lib\site-packages (from scikit-learn>=0.22.0->kmodes) (2.1.0)

,Customer,State,CLV,Coverage,Income,loc_type,monthly_premium,months_last_claim,Months_Since_Policy_Inception,Total_Claim_Amount,Vehicle_Class,avg_vehicle_age
0,BU79786,Washington,2763.519279,Basic,56274,Suburban,69,32,5,384.811147,Two-Door Car,40.696695
1,AI49188,Nevada,12887.431650,Premium,48767,Suburban,108,18,38,566.472247,Two-Door Car,48.755298
2,HB64268,Washington,2813.692575,Basic,43836,Rural,73,12,44,138.130879,Four-Door Car,70.394474
3,OC83172,Oregon,8256.297800,Basic,62902,Rural,69,14,94,159.383042,Two-Door Car,53.460212
4,XZ87318,Oregon,5380.898636,Basic,55350,Suburban,67,0,13,321.600000,Four-Door Car,32.811507

In [3]:
marketing_df=marketing_df.drop(['Customer','Vehicle_Class','avg_vehicle_age','months_last_claim','Total_Claim_Amount'],axis=1)
marketing_df

,State,CLV,Coverage,Income,loc_type,monthly_premium,Months_Since_Policy_Inception
0,Washington,2763.519279,Basic,56274,Suburban,69,5
1,Nevada,12887.431650,Premium,48767,Suburban,108,38
2,Washington,2813.692575,Basic,43836,Rural,73,44
3,Oregon,8256.297800,Basic,62902,Rural,69,94
4,Oregon,5380.898636,Basic,55350,Suburban,67,13
...,...,...,...,...,...,...,...
6812,California,5032.165498,Basic,66367,Suburban,64,48
6813,California,4100.398533,Premium,47761,Suburban,104,58
6814,California,23405.987980,Basic,71941,Urban,73,89
6815,California,3096.511217,Extended,21604,Suburban,79,28
6816,California,7524.442436,Extended,21941,Suburban,96,3

In [4]:
mark_array=marketing_df.values
mark_array

array([['Washington', 2763.519279, 'Basic', ..., 'Suburban', 69, 5],
       ['Nevada', 12887.43165, 'Premium', ..., 'Suburban', 108, 38],
       ['Washington', 2813.692575, 'Basic', ..., 'Rural', 73, 44],
       ...,
       ['California', 23405.98798, 'Basic', ..., 'Urban', 73, 89],
       ['California', 3096.511217, 'Extended', ..., 'Suburban', 79, 28],
       ['California', 7524.442436, 'Extended', ..., 'Suburban', 96, 3]],
      dtype=object)

In [5]:
kproto = KPrototypes(n_clusters=3, verbose=2,max_iter=20)
clusters = kproto.fit_predict(mark_array, categorical=[0, 2, 4])

Init: initializing centroids
Init: initializing clusters
Init: initializing centroids
Init: initializing clusters
Starting iterations...
Run: 1, iteration: 1/20, moves: 724, ncost: 838218878929.7954
Run: 1, iteration: 2/20, moves: 482, ncost: 804773036147.6417
Run: 1, iteration: 3/20, moves: 327, ncost: 790553271916.1119
Run: 1, iteration: 4/20, moves: 165, ncost: 787060161061.7161
Run: 1, iteration: 5/20, moves: 79, ncost: 786125919163.3329
Run: 1, iteration: 6/20, moves: 45, ncost: 785853642322.0415
Run: 1, iteration: 7/20, moves: 37, ncost: 785682196859.6218
Run: 1, iteration: 8/20, moves: 12, ncost: 785652773397.5131
Run: 1, iteration: 9/20, moves: 16, ncost: 785609292387.8527
Run: 1, iteration: 10/20, moves: 13, ncost: 785587014534.571
Run: 1, iteration: 11/20, moves: 6, ncost: 785580196116.0238
Run: 1, iteration: 12/20, moves: 4, ncost: 785577307058.1285
Run: 1, iteration: 13/20, moves: 4, ncost: 785574087818.5052
Run: 1, iteration: 14/20, moves: 3, ncost: 785572843787.3959
Run: 1, iteration: 15/20, moves: 0, ncost: 785572843787.3959
Init: initializing centroids
Init: initializing clusters
Starting iterations...
Run: 2, iteration: 1/20, moves: 748, ncost: 831508349099.5311
Run: 2, iteration: 2/20, moves: 459, ncost: 801278128179.1622
Run: 2, iteration: 3/20, moves: 303, ncost: 790609059624.2255
Run: 2, iteration: 4/20, moves: 162, ncost: 787331663278.2163
Run: 2, iteration: 5/20, moves: 93, ncost: 786183724462.9106
Run: 2, iteration: 6/20, moves: 67, ncost: 785655956320.5769
Run: 2, iteration: 7/20, moves: 26, ncost: 785566620155.142
Run: 2, iteration: 8/20, moves: 10, ncost: 785551468522.3029
Run: 2, iteration: 9/20, moves: 6, ncost: 785546422486.7773
Run: 2, iteration: 10/20, moves: 2, ncost: 785545634415.1555
Run: 2, iteration: 11/20, moves: 0, ncost: 785545634415.1555
Init: initializing centroids
Init: initializing clusters
Starting iterations...
Run: 3, iteration: 1/20, moves: 1122, ncost: 897919711421.0046
Run: 3, iteration: 2/20, moves: 753, ncost: 819714991761.704
Run: 3, iteration: 3/20, moves: 422, ncost: 796587103329.1543
Run: 3, iteration: 4/20, moves: 247, ncost: 788370873771.5142
Run: 3, iteration: 5/20, moves: 103, ncost: 786712261640.0181
Run: 3, iteration: 6/20, moves: 68, ncost: 786018749473.7969
Run: 3, iteration: 7/20, moves: 49, ncost: 785740155958.5568
Run: 3, iteration: 8/20, moves: 28, ncost: 785655117685.776
Run: 3, iteration: 9/20, moves: 15, ncost: 785613961116.1898
Run: 3, iteration: 10/20, moves: 15, ncost: 785587014534.5712
Run: 3, iteration: 11/20, moves: 6, ncost: 785580196116.0238
Run: 3, iteration: 12/20, moves: 4, ncost: 785577307058.1284
Run: 3, iteration: 13/20, moves: 4, ncost: 785574087818.5052
Run: 3, iteration: 14/20, moves: 3, ncost: 785572843787.3959
Run: 3, iteration: 15/20, moves: 0, ncost: 785572843787.3959
Init: initializing centroids
Init: initializing clusters
Starting iterations...
Run: 4, iteration: 1/20, moves: 2103, ncost: 790777627101.8749
Run: 4, iteration: 2/20, moves: 318, ncost: 785637383240.1993
Run: 4, iteration: 3/20, moves: 34, ncost: 785566723216.9838
Run: 4, iteration: 4/20, moves: 14, ncost: 785541472267.1284
Run: 4, iteration: 5/20, moves: 2, ncost: 785540918453.7346
Run: 4, iteration: 6/20, moves: 0, ncost: 785540918453.7346
Init: initializing centroids
Init: initializing clusters
Starting iterations...
Run: 5, iteration: 1/20, moves: 376, ncost: 789180265205.1813
Run: 5, iteration: 2/20, moves: 132, ncost: 786792508072.2992
Run: 5, iteration: 3/20, moves: 73, ncost: 786029124875.1241
Run: 5, iteration: 4/20, moves: 51, ncost: 785740155958.557
Run: 5, iteration: 5/20, moves: 28, ncost: 785655117685.7759
Run: 5, iteration: 6/20, moves: 15, ncost: 785613961116.1896
Run: 5, iteration: 7/20, moves: 15, ncost: 785587014534.5714
Run: 5, iteration: 8/20, moves: 6, ncost: 785580196116.0237
Run: 5, iteration: 9/20, moves: 4, ncost: 785577307058.1284
Run: 5, iteration: 10/20, moves: 4, ncost: 785574087818.5054
Run: 5, iteration: 11/20, moves: 3, ncost: 785572843787.3959
Run: 5, iteration: 12/20, moves: 0, ncost: 785572843787.3959
Init: initializing centroids
Init: initializing clusters
Starting iterations...
Run: 6, iteration: 1/20, moves: 1360, ncost: 891125448051.596
Run: 6, iteration: 2/20, moves: 673, ncost: 825339777442.9564
Run: 6, iteration: 3/20, moves: 456, ncost: 798811807747.1664
Run: 6, iteration: 4/20, moves: 268, ncost: 790092696103.0632
Run: 6, iteration: 5/20, moves: 150, ncost: 787227856431.5718
Run: 6, iteration: 6/20, moves: 88, ncost: 786150982767.1937
Run: 6, iteration: 7/20, moves: 65, ncost: 785652190455.6047
Run: 6, iteration: 8/20, moves: 25, ncost: 785566620155.1418
Run: 6, iteration: 9/20, moves: 10, ncost: 785551468522.3031
Run: 6, iteration: 10/20, moves: 6, ncost: 785546422486.7771
Run: 6, iteration: 11/20, moves: 2, ncost: 785545634415.1554
Run: 6, iteration: 12/20, moves: 0, ncost: 785545634415.1554
Init: initializing centroids
Init: initializing clusters
Starting iterations...
Run: 7, iteration: 1/20, moves: 1358, ncost: 866948223176.3774
Run: 7, iteration: 2/20, moves: 626, ncost: 812668439279.5042
Run: 7, iteration: 3/20, moves: 388, ncost: 793893958777.375
Run: 7, iteration: 4/20, moves: 202, ncost: 788670207599.9241
Run: 7, iteration: 5/20, moves: 119, ncost: 786794545041.5863
Run: 7, iteration: 6/20, moves: 81, ncost: 785903097925.9777
Run: 7, iteration: 7/20, moves: 51, ncost: 785606912443.415
Run: 7, iteration: 8/20, moves: 18, ncost: 785557453367.9038
Run: 7, iteration: 9/20, moves: 7, ncost: 785550664653.3425
Run: 7, iteration: 10/20, moves: 7, ncost: 785545634415.1554
Run: 7, iteration: 11/20, moves: 0, ncost: 785545634415.1554
Init: initializing centroids
Init: initializing clusters
Starting iterations...
Run: 8, iteration: 1/20, moves: 454, ncost: 788338217982.0497
Run: 8, iteration: 2/20, moves: 102, ncost: 786724122506.1993
Run: 8, iteration: 3/20, moves: 69, ncost: 786018749473.7964
Run: 8, iteration: 4/20, moves: 49, ncost: 785740155958.5568
Run: 8, iteration: 5/20, moves: 28, ncost: 785655117685.7759
Run: 8, iteration: 6/20, moves: 15, ncost: 785613961116.1893
Run: 8, iteration: 7/20, moves: 15, ncost: 785587014534.5712
Run: 8, iteration: 8/20, moves: 6, ncost: 785580196116.0236
Run: 8, iteration: 9/20, moves: 4, ncost: 785577307058.1285
Run: 8, iteration: 10/20, moves: 4, ncost: 785574087818.5051
Run: 8, iteration: 11/20, moves: 3, ncost: 785572843787.3959
Run: 8, iteration: 12/20, moves: 0, ncost: 785572843787.3959
Init: initializing centroids
Init: initializing clusters
Starting iterations...
Run: 9, iteration: 1/20, moves: 630, ncost: 800484503200.0839
Run: 9, iteration: 2/20, moves: 303, ncost: 789231575095.6957
Run: 9, iteration: 3/20, moves: 133, ncost: 786810028279.4452
Run: 9, iteration: 4/20, moves: 74, ncost: 786029124875.1241
Run: 9, iteration: 5/20, moves: 51, ncost: 785740155958.557
Run: 9, iteration: 6/20, moves: 28, ncost: 785655117685.7759
Run: 9, iteration: 7/20, moves: 15, ncost: 785613961116.1897
Run: 9, iteration: 8/20, moves: 15, ncost: 785587014534.5713
Run: 9, iteration: 9/20, moves: 6, ncost: 785580196116.0238
Run: 9, iteration: 10/20, moves: 4, ncost: 785577307058.1287
Run: 9, iteration: 11/20, moves: 4, ncost: 785574087818.5052
Run: 9, iteration: 12/20, moves: 3, ncost: 785572843787.3959
Run: 9, iteration: 13/20, moves: 0, ncost: 785572843787.3959
Init: initializing centroids
Init: initializing clusters
Starting iterations...
Run: 10, iteration: 1/20, moves: 1423, ncost: 797389651576.146
Run: 10, iteration: 2/20, moves: 248, ncost: 788881915416.7804
Run: 10, iteration: 3/20, moves: 123, ncost: 786809122695.0828
Run: 10, iteration: 4/20, moves: 82, ncost: 785903097925.9777
Run: 10, iteration: 5/20, moves: 51, ncost: 785606912443.4147
Run: 10, iteration: 6/20, moves: 18, ncost: 785557453367.9036
Run: 10, iteration: 7/20, moves: 7, ncost: 785550664653.3424
Run: 10, iteration: 8/20, moves: 7, ncost: 785545634415.1555
Run: 10, iteration: 9/20, moves: 0, ncost: 785545634415.1555
Best run was number 4

In [6]:
print(kproto.cluster_centroids_)

[['8035.160144780605' '26660.126312106368' '92.62491252624213'
  '46.98040587823653' 'California' 'Basic' 'Suburban']
 ['8319.719778556962' '54736.470943747096' '95.09437470943747'
  '49.14923291492329' 'California' 'Basic' 'Suburban']
 ['8055.071059713492' '82981.0392699115' '90.96183628318585'
  '47.61338495575221' 'California' 'Basic' 'Suburban']]

In [7]:
cluster_dict=[]
for c in clusters:
    cluster_dict.append(c)

In [8]:
marketing_df['cluster']=cluster_dict
marketing_df

,State,CLV,Coverage,Income,loc_type,monthly_premium,Months_Since_Policy_Inception,cluster
0,Washington,2763.519279,Basic,56274,Suburban,69,5,1
1,Nevada,12887.431650,Premium,48767,Suburban,108,38,1
2,Washington,2813.692575,Basic,43836,Rural,73,44,1
3,Oregon,8256.297800,Basic,62902,Rural,69,94,1
4,Oregon,5380.898636,Basic,55350,Suburban,67,13,1
...,...,...,...,...,...,...,...,...
6812,California,5032.165498,Basic,66367,Suburban,64,48,1
6813,California,4100.398533,Premium,47761,Suburban,104,58,1
6814,California,23405.987980,Basic,71941,Urban,73,89,2
6815,California,3096.511217,Extended,21604,Suburban,79,28,0
6816,California,7524.442436,Extended,21941,Suburban,96,3,0